### ISSUE TITLE
[Parsing] default file block parsing

### ISSUE THREAD

**Issue by DBrider3** [WebservDreamTeam/DreamXWebserv#12]
- [x] http block parsing
- [x] server block parsing
- [x] location block parsing

**Comment by DBrider3** [comment]
🐶 dchosonchokang's Parsing Team (DPT) 🐹
sonkang님 정말 수고 많으셨습니다!

**Comment by xhseb** [comment]
> 🐶 dchosonchokang's Parsing Team (DPT) 🐹
> sonkang님 정말 수고 많으셨습니다!

dcho님도 수고 많으셨습니다!👼
