### ISSUE TITLE
[Bug] Read Error

### ISSUE THREAD

**Issue by DBrider3** [WebservDreamTeam/DreamXWebserv#41]
### Read() 끝나는 시점을 못 찾는 issue
동적인 페이지를 처리하는 CGI Part에서 응답파싱을 임시방편으로 하기위해 응답 사이즈를 임의로 측정함.
그 결과 php 함수에서 정확하게 사이즈 측정이 불가능 하기에 처리가 안됨. 

- 원인 추론
22.04.11 : 환경 문제로 판단이 되고 있음. iMac에서 확인해 볼 필요성을 느낌.

**Comment by xhseb** [comment]
pipe()함수를 이용후 fd를 활용해서 read()함수를 while로 돌리면 함수탈출이 안되었다.
고수준 파일 입출력을 이용해 파일 지시자를 다르게 쓰고 그 속에서 fd를 활용한 결과 잘 해결이 되었다.
