### ISSUE TITLE
[Refactor] re-use client_fd & client_control

### ISSUE THREAD

**Issue by jungmyeong96** [WebservDreamTeam/DreamXWebserv#71]
- [x] 생성된 client를 여러 요청을 처리할 수 있도록 재사용시켜줌.
- [x] client가 요청을 응답한 뒤, 데이터백인 client_control을 초기화시켜줌
- [x] client의 read()가 0일때 disconnect되는 부분을 수정해줘야함.
- [x] 프로그램이 끝나기 전까지 하나의 client가 살아있어야함.

**Comment by DBrider3** [comment]
[Fix : disconnect client when read return 0](https://github.com/WebservDreamTeam/DreamXWebserv/commit/91e22aff11de3fe36627edcad149df09522ad241)
이후 처리할 내용: 
- disconnected할때 fd가 쌓이지 않고 fd 5번이 마지막에 disconnected 되어야함.
- 속도 개선
- 리팩토링
